### ISSUE TITLE
 Facebook feed is only pulling photo updates

### ISSUE THREAD

**Issue by iatek** [iatek/jquery-socialist#1]
Kelsey Wynns notified me of this via email. I wouldn't categorize this as "by design", but there is also no immediate "fix".

The FB Graph API only allows open access (no auth key required) on the "photos" and "albums" page feeds http://developers.facebook.com/docs/reference/api/page/#connections

Since Socialist is intended for public feeds (it doesn't provide any auth) it does not aggregate other FB feeds that may contain more fields of interest from the Pages API (ie; title, description, caption, etc..). However, I may develop a goodie/plugin for in1(http://beta.in1.com) that does implement this eventually.

**Comment by matteopoile** [comment]
Any news about the plugin to integrate post from FB?

**Comment by karthikc001** [comment]
Isn't it possible to have access to a Wall feed as long as we pass a valid access token for our own Facebook page? So, if we have a Facebook Page already, it appears that passing the Page's access token will work: "For connections that require an access token, you can use any valid access token if the page is public and not restricted. Connections on restricted pages require a user access token and are only visible to users who meet the restriction criteria (e.g. age) set on the page."

**Comment by matteopoile** [comment]
Tahnks a lot karthikc, very interesting.
At the end I decide to download the php sdk and connect to FB "seriously".
Now I have some problem with the post pictures, too small to be reused in my web page; I think I have to use the object_id and another api call to get the bigger pictures
