### ISSUE TITLE
issue with twitter

### ISSUE THREAD

**Issue by kamov** [iatek/jquery-socialist#11]
Hi,

using account for twitter there is error and blank page

**Comment by danbeazley** [comment]
I'm also having an issue with twitter. It works fine with normal user names, but when I try to use it with a user name such as  this_user (with a _ in it) it does not work.

**Comment by iatek** [comment]
Haven't had time to look at this yet, but home to soon.

**Comment by kamov** [comment]
Hi iatek,

Don't worry. Take your time! I am so excited about your plugin and can't wait new release.

Compliment!

Just a question, in1.com will become a new social network? like social of socials?

I see you have introduce new feature like publish on social media from external sites.

Do you plan release a version like jquery socialist? free to use?

Thanks

**Comment by danbeazley** [comment]
Ditto what Kamov said. This plugin will be worth the wait. thanks for working on it. 

Dan

**Comment by iatek** [comment]
I have made recent updates for Twitter so I'm closing this for now.
