### ISSUE TITLE
example blank, test page blank...please~~~

### ISSUE THREAD

**Issue by hegler02** [iatek/jquery-socialist#12]
The example - index.html - loads a blank page in all browsers.
This doesn't work.

Please, fix it.

Thanks.

http://64.23.76.49/socialstream/test_01.html

http://64.23.76.49/socialstream/index2.html

http://64.23.76.49/socialstream/test_03.html

every page is blank... ㅠ.ㅠ

**Comment by iatek** [comment]
Did you include jquery? This reference is missing from the example, and I've not had time to update it yet. All should work if you add a jquery script reference.

**Comment by hegler02** [comment]
Thanks iatek.
It has 3 jQuary in this source.
but example has two jQuary.
I will try.

**Comment by iatek** [comment]
You're welcome and you can follow us on http://facebook.com/in1dotcom too!

Carol Skelly
Founder in1.com

**Comment by hegler02** [comment]
I already liked your fan page. Social stream is very fantastic.
I want to do this.
I have a question.
Does social stream has comment(facebook,pinterest etc)???

Is it adapted 'JSP'

**Comment by hegler02** [comment]
ㅠ.ㅠ..

my source...What's the problem???

still~~~ blank!!!

**Comment by jamesabruce** [comment]
You haven't included jQuery, as iatek explained. Please add this line to the header:

``` html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
```

**Comment by hegler02** [comment]
@jamesabruce  Thank you very much~~~~ ^^

**Comment by iatek** [comment]
Thanks.. closing this.
