### ISSUE TITLE
Flickr

### ISSUE THREAD

**Issue by kamov** [iatek/jquery-socialist#13]
Hi,

When I try use flickr there is this error message:

{"stat":"fail", "code":100, "message":"Invalid API Key (Key has invalid format)"}

Is required API key for flickr?

Thanks

**Comment by iatek** [comment]
Yes. It would be your Flickr API key, and you set the value using "apiKey" in your networks:{}..

{name:'flickr', id:'flickrusername', apiKey:'myapikeyhere'}

**Comment by kamov** [comment]
Hi, thanks for reply. Yes, I get it work and forgot reply here about.
Thanks!
