### ISSUE TITLE
Problem with a specific rss 

### ISSUE THREAD

**Issue by matteopoile** [iatek/jquery-socialist#19]
It seems it doesn't work with this rss: https://www.facebook.com/feeds/page.php?id=190492364339566&format=rss20.

It's a valid rss but doesn't work with socialist.

**Comment by vectorlost** [comment]
Hi! I'm having the same problem (I think). I'm trying to get this to work: 
_http://ws.audioscrobbler.com/2.0/user/vectorlost/recenttracks.rss_

Like matteopoile, it's a valid rss that seems to return the following file:
_recenttracks.rss.webintents_

Any clues?

**Comment by iatek** [comment]
Currently RSS goes throught the Google Feeds API so if Google is not able to index the feed, it won't work.

@matteopoile - For whatever reason Google can't load RSS from Facebook (https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&q=https://www.facebook.com/feeds/page.php?id=190492364339566&format=rss20), so there is not too much I can do with that.

@vectorlost - The feed you provided loads fine via Google (https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&q=http://ws.audioscrobbler.com/2.0/user/vectorlost/recenttracks.rss) -- so there must me something specific in the content that I'll need to track down.. This will take some time, but I will look at it the next few weeks.

**Comment by matteopoile** [comment]
The problem with my feed was that facebook check the user agent.

**Comment by iatek** [comment]
Closing this -- seems to be resolved.
