### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ova2** [iatek/jquery-socialist#2]
Hi Carol,

Thanks for this great plugin first! We have a component set for Java / Web development http://code.google.com/p/primefaces-extensions/ and I plan to use your plugin too. But I can't find any infos regarding license? Is it free? Can you maybe add a license note? We prefer the same license as jQuery http://jquery.org/license/ (MIT + GPL) or Apache.

Many thanks in advance.

P.S. I would also separate dependency files from the core plugin (as separate files) because if somebody already has these dependencies, he / she doesn't need to include them again.

**Comment by iatek** [comment]
The MIT license info has been added. However, the included jQuery Isotope plugin does require a license fee for commercial use (http://metafizzy.co/#licenses)
