### ISSUE TITLE
Random, but sorted by date

### ISSUE THREAD

**Issue by vectorlost** [iatek/jquery-socialist#20]
Hi! I'm trying to get different feeds displayed randomly...but ordered by chronological date.

Example: trying to get my output displayed in this order -->
_Youtube video2 - october 23
Twitter post3 - october 23
Twitter post2- october 23
Twitter post1 - october 19
Youtube video1 - october 6_

Would it be possible?

**Comment by iatek** [comment]
Not at this time. I will consider it for future updates.
