### ISSUE TITLE
Blank Page error still :@

### ISSUE THREAD

**Issue by sanketfirodiya** [iatek/jquery-socialist#21]
I am still stuck with the blank page issue, tried following steps of including the latest jquery as mentioned in previous issue list but nothing has worked yet.

Can someone please link me to their working example page or suggest what I might be missing?

Thanks a ton!!

**Comment by jamesabruce** [comment]
How about you post your example somewhere and we'll tell you what's wrong?

**Comment by sanketfirodiya** [comment]
I actually looked at the html of the link mentioned in issue #3 and it started working then, looks like one of the user ids in the example file is corrupt causing the plugin to fail.
btw on a different note, have you tried setting up a timed ajax request to refresh the feed every x seconds or something like that?
would you know where I could tweak the plugin for such a feature?

Once again thanks a lot!!
