### ISSUE TITLE
Hashtag and link for twitter

### ISSUE THREAD

**Issue by Gornova** [iatek/jquery-socialist#23]
Hi! socialist is very interesting, but I've not found how to have useable link from twiter, in particular: hashtags, links, people cite 

do you plan to integrate in the future?

thanks!

**Comment by iatek** [comment]
I'm considering this (hashtags specifically) but and going to close this issue since it is the same as issue #18

Please watch https://github.com/iatek/jquery-socialist/issues/18 for updates.
