### ISSUE TITLE
Help to créate Random RSS

### ISSUE THREAD

**Issue by nicemen** [iatek/jquery-socialist#25]
Hi, I would like to create a function to display 1 RSS random among a 3 streams !
! but I do not know much about javascript function I looked random but I can not fit the script can you help me ? 
Give me the solution !? thank

**Comment by iatek** [comment]
From 1 RSS feed, or 3 RSS feeds?

**Comment by nicemen** [comment]
Humm for test 3 Feed in list & 1 extract to list for displays !
Thanks
