### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sgordon1** [iatek/jquery-socialist#27]
Hi.  I am trying to implement the jquery-socialist wall on my new homepage for my website (http://farmiemarket.com/FM/HomeNew.html).  My website is designed using iWeb.  To insert the wall, I uploaded the files and folders inside the "iatek-jquery-socialist-be9e47c" directory I downloaded to the file folder where my new homepage files are located via FTP.  Then, I inserted an HTML Snippet in iWeb with the following code linked here https://github.com/iatek/jquery-socialist/blob/master/examples/index.html updated to reflect my contect (ex:  {name:'facebook',id:'farmiemarket'},).  After uploading the new content, my social wall is not showing up on the new homepage.  It should appear under the "Enter your zip code to connect with the farms most local to you" line.  Can you tell me what I'm doing wrong?  Thank you for your time and work!

**Comment by jamesabruce** [comment]
You have too many slashes in your socialist.js and css reference, heres the errors on the console:

Failed to load resource: the server responded with a status of 404 (Not Found) http://farmiemarket.com/FM//jquery.socialist.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://farmiemarket.com/FM//jquery.socialist.js

**Comment by sgordon1** [comment]
The code doesn't appear to have extra slashes- where should I make the change in the code?

**Comment by jamesabruce** [comment]
Hmm, good point. That's a quirk of using iWeb, I guess. The site is pretty simple, why not just hand code it? Or output what you have no, and manually adjust it.

**Comment by sgordon1** [comment]
I edited the code on my cPanel.  I use iWeb because I'm not much of a coder, and it allows me to drag and drop what I need without hiring someone to write my website.  After editing the code, I am now showing signs that the jquery box is on the site, however is populated with a loading wheel that never seems to load.  Any suggestions?  Thanks!

**Comment by jamesabruce** [comment]
Could be a particular feed having problems. Try commenting all but one out. It's very difficult to debug your site with all the random widget frames. Really, look into using Wordpress; the templates are easy enough to edit.

**Comment by iatek** [comment]
Inactive thread.. will reopen if needed
