### ISSUE TITLE
Very basic help needed!

### ISSUE THREAD

**Issue by jivewebsites** [iatek/jquery-socialist#28]
Hi,
I'm not experienced in jquery and javascript and need some very simple instructions on how to install this on my website. 
Ie. where does the code go header/body etc.
I've uploaded the files to my server and have added the code to this page but it is not working: http://www.jivewebsites.net/socialupdates.htm
Can you please give me some tips.
Thank you!

**Comment by iatek** [comment]
The alternate hosted version may work better for you. It auto loads the jquery, plugin etc..

Just add this to your HTML HEAD section:
<code>
&lt;script type="text/javascript" src="http://plugins.in1.com/scripts/socialist.js">&lt;/script>
  </code>

Then somewhere in the BODY you need a DIV with id="socialist":
<code>
&lt;div id="socialist" data-networks="pinterest,rss,tumblr" data-ids="hubspot,http://feeds2.feedburner.com/ImpressiveWebs,in1blog">&lt;/div>
</code>

Use the "data-networks" and "data-ids" in the DIV tag to define which feeds you want. The order of the networks needs to match the order of the ids so in the example above Pinterest=hubspot

**Comment by jivewebsites** [comment]
Thank you so much Iatek! 

I will give it a go. 

Great work! 

Kind
regards, 

Jeanelle 

---

jive _websites_ ~ gets your site live
 M: +61
402302378
 Skype: j-nelle07 
Address: Suite A, 43/49 Mitchell Rd,
Brookvale NSW 2100
 WWW.JIVEWEBSITES.NET [2] 

 [3] [4] [5] 
CONNECT
with me to receive free web tips and answers to your web questions -
just post it on my Facebook, Twitter or linkedIN pages! 

On 2012-11-10
02:29, Carol Skelly wrote: 

> The alternate hosted version may work
> better for you. It auto loads the jquery, plugin etc.. 
> 
> Just add
> this to your HTML HEAD section: 
> 
> Then somewhere in the BODY you
> need a DIV with id="socialist": 
> 
> Use the "data-networks" and
> "data-ids" in the DIV tag to define which feeds you want. The order of
> the networks needs to match the order of the ids so in the example above
> Pinterest=hubspot 
> 
> ## 
> 
> Reply to this email directly or view it on
> GitHub [1].

## Links:

[1]
https://github.com/iatek/jquery-socialist/issues/28#issuecomment-10232258
[2]
http://www.jivewebsites.net
[3]
http://www.facebook.com/jivewebsites
[4] http://twitter.com/jijive
[5]
http://www.linkedin.com/profile/view?id=9284116
