### ISSUE TITLE
Only able to get one pic from Facebook and incomplete twitter feed?

### ISSUE THREAD

**Issue by matthewatdf** [iatek/jquery-socialist#31]
I've been testing out various jQuery plugins for pulling Twitter and Facebook feeds. All have been pulling the expected updates, except for Socialist.

Here's my test code:

`$(document).ready(function () {
    $('#content').socialist({
        networks: [
            {name:'facebook',id:'flysouthisland'},
            {name:'twitter',id:'flysouthisland'},
           ],
        isotope:false,
        random:false,
        fields:['source','heading','text','date','image','followers','likes']
    });
});``

Test page: http://flysouthisland.co.nz/include/demo/examples/

It's only getting one picture from facebook and a couple of Tweets. What am I missing?

**Comment by iatek** [comment]
Hi,

At this time, the only public feed (one that doesn't require authentication) from Facebook is the "photos" feed. We can only pull photos that you (FlyIslandSouth) posted, therefore updates and shared photos are not in the feed. Eventually I hope FB will provide more in the public feed, or we may try some auth.

For Twitter, I have pushed an update that will include RT's so you should see more Twitter results. Use the MaxResults options (default=7) if you wish to get more.
