### ISSUE TITLE
Instagram?

### ISSUE THREAD

**Issue by piquebug** [iatek/jquery-socialist#32]
Just pulled the latest and although it says in the wiki that socialist pulls instagram, I'm not seeing anything for instagram in the jquery or displayed as a sample. ("Display Instagram photos in Pinterest-style layouts") although it does look like the in1.com site might have both instagram and facebook feeds working properly, I'm not able to get either to work properly in the sample (already noted the issue previously posted regarding Facebook elsewhere on the issues forum). Are there any plans to add instagram, or am I missing some simple way of adding it to the feed?

Thanks

**Comment by iatek** [comment]
Instagram support added for a tag/keyword. Eventually I'll be adding support for specific user id's.
