### ISSUE TITLE
Blank Page Even with JQuery.js

### ISSUE THREAD

**Issue by Strydom** [iatek/jquery-socialist#33]
Hi i am trying to get this to work on my home WAMP sever but i keep getting a blank page. i have the latest version of socialist which already includes JQuery.js I'm using the example as it comes. Running it on Firefox 17.01.

I Dont know why it wont work :zzz:

**Comment by iatek** [comment]
Do you have Firebug installed? Can you provide any more error details? Which API's are you attempting? This will work, it may be a path issue or something?

**Comment by Strydom** [comment]
The only error firebug came up with is this...

ReferenceError: $ is not defined
$(document).ready(function () {
index.html (line 8)

As for API's I'm simple trying to run the default Example that you provide... Index.HTML

**Comment by Strydom** [comment]
Never mind i found out that i needed all of the files to be in the same folder and i needed the Jquery.min on my server and not get it from the web. it didn't have enough time to get them.

**Comment by Strydom** [comment]
Everyone who is having this problem or similar go see my response in issue https://github.com/iatek/jquery-socialist/issues/29
