### ISSUE TITLE
Pinterest Date Selector

### ISSUE THREAD

**Issue by kmusch** [iatek/jquery-socialist#38]
I would like to have a date in the pinterest display. 
In the js, pinterest doesn't have the dataSelector. What is the best way to add that in? 

It should be similar to how twitter is working...I used the flickr dateSelector: "new Date(item.dateupload)", but of course it isn't setup so it displays invalid date.

Any simple code here I could use?
Thanks

**Comment by iatek** [comment]
Pinterest doesn't seem to provide date on the pinboards, therefore no way (currently) to get date. I will reopen if they introduce a date field.
