### ISSUE TITLE
I can't connect to the facebook account that I want to publish

### ISSUE THREAD

**Issue by OrlandoBiondi** [iatek/jquery-socialist#39]
I can run the example properly, but I can't connect to the facebook account that I want to publish.

I explain better, the standard example is linked to an account called "in1dotcom".
Where can I find the corresponding account name on my private facebook profile ?

Moreover, considering the example pulling info from "in1dotcome", I've seen that not all existing posts will be published through your script, but only n°3 posts.
Are these 3 posts different from other ones?
Which features do these posts have in order to be published?

I look forward to heraing from you soon

**Comment by iatek** [comment]
It simply uses the name of the Facebook Page.

It will only pull photo updates at this time. Pls see this issue: https://github.com/iatek/jquery-socialist/issues/1
