### ISSUE TITLE
RSS with undefined link

### ISSUE THREAD

**Issue by miskei** [iatek/jquery-socialist#41]
I never thought I'd ever right this down but I love the sociaIist. :)

I have a little issue though. 

I have 2 RSS feeds. One works properly, well not really, there is only the headline, and another that displays nicely but all the links are blank leading to 404. What can cause this?

**Comment by gunbunnysoulja** [comment]
I have the same undefined issue for most of my desired RSS feeds, including:

http://feeds.feedburner.com/ArtNewsTheartwolfcom format=xml
http://www.theartnewspaper.com/rss/rss.xml
http://www.artnews.com/feed/
http://rss.artinfo.com/artinfo-all?format=xml

Yahoo and the huffington post seems to work for me, although I did notice a couple links return as undefined.

**Comment by iatek** [comment]
Is this working now? I've tested in Chrome and they seem okay:

http://jsfiddle.net/skelly/4R4Ss/3/

**Comment by miskei** [comment]
Hi, I checked your fiddle. The google feed is fine, the RSS feeds, Art Info, if it was with a picture it seems fine, without all show undefined. Chrome, Firefox, Safari.

Mine still doesn't work. Still undefined. Problem only with some RSS, but I couldn't figure out if they were any specific format. And this might help, but those with undefined URL, show a blank tooltip.

**Comment by iatek** [comment]
Are you using the latest jquery.socialist.js (not .min.js) ?

**Comment by miskei** [comment]
No, I use 1.01 and not the .min. Just to make sure I copied over the code you have posted here as latest. All is the same. I also tried to put my link in question into your fiddle. Still undefined. Thanks.

**Comment by miskei** [comment]
OK, I sorted the undefined RSS problem. I changed line 320 in the jquery.socialist.js file to imgHrefSelector: "item.link", now they link correctly.
