### ISSUE TITLE
pinterest doesn't work properly

### ISSUE THREAD

**Issue by eastsidegraphics** [iatek/jquery-socialist#43]
I get a blank page each time I try to use a pinterest id. I applied the suggestions from issue #29 - no luck.
I noticed that in 'jquery.socialist.js' the pinterest DataType is "text". I changed it to "jsonp"... no luck.
My test page is at http://www.eastsidegraphics.com/socialist/
Please advise.

**Comment by iatek** [comment]
What Pinterest id are you attempting to use?

**Comment by eastsidegraphics** [comment]
officiallfc/pins/

**Comment by iatek** [comment]
This seems to work for me (using Chrome or FF): http://jsfiddle.net/skelly/4R4Ss/4/

Are you using jquery.socialist.min.js or jquery.socialist.js ?

**Comment by eastsidegraphics** [comment]
I use jquery.socialist.js

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link href="jquery.socialist.css" rel="stylesheet" />

<script src="jquery.min.js" type="text/javascript"></script>

<script src='jquery.socialist.js'></script>

<script type="text/javascript">
$(document).ready(function () {
    $('#content').socialist({
        networks: [
            {name:'rss',id:'http://rss.cnn.com/rss/edition.rss'},
            {name:'pinterest',id:'officiallfc/pins/'}
           ],
        random:false,
        fields:['source','heading','text','date','image']
    });
});
</script>

</head>
<body>
    <div id="content"></div>
</body>
</html>

It doesn't work on FF, IE or Chrome...

**Comment by iatek** [comment]
Use id:'officiallfc/pins' instead of id:'officiallfc/pins/'

**Comment by eastsidegraphics** [comment]
I changed the id - still doesn't work. Can you please check the source of http://www.eastsidegraphics.com/socialist/ and tell me if the code is ok?

**Comment by iatek** [comment]
It works for fine me in FF 18 and Chrome. What browser are you using?

**Comment by iatek** [comment]
Please let me know if this is working for you so that I can close it out.

**Comment by eastsidegraphics** [comment]
Unfortunately it doesn't work. I tried other pinterest ids... it simply doesn't work. When I remove the pintertest id the socialist widget works ok. Only pinterest seems to be the problem with me.
I use Firefox 18.0.2, IE 8, Chrome 24.0.1312.57 m

**Comment by iatek** [comment]
It works for me even when I hit http://www.eastsidegraphics.com/socialist/

Did you clear your browser cache? Since there is nothing to "fix" on this end I will close this as an issue.

**Comment by ValeryCC** [comment]
Hi,

First this looks like a fantastic plugin!  I think it needs more documentation though.

I can't get my pinterest to work either.  Can you explain what all the id's mean for each social media?

**Comment by gojo23** [comment]
My Pinterest isn't working correctly either. Even if I check http://jsfiddle.net/skelly/4R4Ss/4/ it works then it doesn't if refreshed. It seems temperamental! Any help for a fix would be great.
