### ISSUE TITLE
Two Twitter Networks

### ISSUE THREAD

**Issue by cerw** [iatek/jquery-socialist#47]
Hi I love your plugin I am trying to use 2 twitter account and it seems only one is showing? 

```
                networks: [ 
                    {name:'twitter', id: 'SLS_Online'},
                    {name:'twitter', id: 'SLSWA'},
                    {name:'facebook', id: 'lifesaving'},
                    {name:'rss', id: 'http://sls.com.au/rss/articles/all'}
                ],
```

thanks

**Comment by cerw** [comment]
Is this possible with this plugin?

**Comment by iatek** [comment]
Yes, this should work.

**Comment by cerw** [comment]
but it does not, any 2nd twitter account does not do anything?

On 12/02/2013, at 8:07 PM, Carol Skelly notifications@github.com wrote:

> Yes, this should work.
> 
> —
> Reply to this email directly or view it on GitHub.

petr červenka
website development

macdaddy pty ltd
sydney  +61 2 8314 1008
perth   +61 8 6420 0468
prague  +420 2 26 531 406
fax         +61 2 9130 5767
mob     +61 0430 007 831
email petr@ʎppɐpɔɐɯ.com
3/ 88 brighton bvd, bondi beach nsw 2026
 www.macdaddy.com.au

The contents of this e-mail are confidential. If you are not the intended
recipient, you must not disclose, copy or use the contents in any way.If
this is the case please contact the sender immediately. Any views 
expressed in this e-mail are not to be taken as the views of the company.

P  Please consider the environment before you print this email.

**Comment by iatek** [comment]
2 or more Twitter networks does work: http://jsfiddle.net/skelly/4R4Ss/1/

There is something about the @SLSWA account that is doesn't like (http://jsfiddle.net/skelly/4R4Ss). I will investigate further and keep you posted.

**Comment by iatek** [comment]
I have posted the update to jquery.socialist.js -- The problem was caused when the Twitter account had posts without links (like @SLSWA). 'http://twitter.com/screename' is now used to construct the link when the Twitter post contains no link.

**Comment by cerw** [comment]
Thank you :+1:

**Comment by cerw** [comment]
HI @iatek  thanks for the update, it does how now, hoever it's only showing older tweets? Is there a cache or something? Check updates gits http://jsfiddle.net/4R4Ss/5/

Thanks
Petr
