### ISSUE TITLE
Facebook feeds not pulling in latest posts...(again)

### ISSUE THREAD

**Issue by hutber** [iatek/jquery-socialist#57]
Hi, 

thanks first of all for putting together this plugin. Its lovely.

Just one question, i know this issue: https://github.com/iatek/jquery-socialist/issues/1 already addresses the issue. Stating that as, without auth, its impossible to pulling in posts without having any auth. 

But on my page, the posts are indeed public, and are still not being picked up. The only posts that are being picked up are the profile picture album. Nothing else...

Sorry to pesture you, just very interested in getting this addressed in a sense of understanding if its unfixable.

Cheers

Jamie

**Comment by ValeryCC** [comment]
I have the same issue.  It's only pulling up pictures that are a year old, and random ones too.  Is there going to be a fix for this?

**Comment by iatek** [comment]
Are the only "photos" on your Facebook page a year old. Again, without auth the only thing that FB makes available are "photos" -- not "posts", "news", "status", etc..

**Comment by ValeryCC** [comment]
There FB are more recent photos available, but it's not pulling those up for some reason.  So how do you add the auth for FB?
