### ISSUE TITLE
Uncaught ReferenceError: item is not defined

### ISSUE THREAD

**Issue by samme** [iatek/jquery-socialist#6]
I see this error on http://plugins.in1.com/socialist/demo

<pre>Uncaught ReferenceError: item is not defined  jquery.socialist.js:48
  $.fn.socialist.methods.init                 jquery.socialist.js:48
  e.extend.each                               jquery.min.js:2
  e.fn.e.each                                 jquery.min.js:2
  $.fn.socialist.methods.init                 jquery.socialist.js:24
  $.fn.socialist                              jquery.socialist.js:567
  (anonymous function)                        demo:42
  f.Callbacks.n                               jquery.min.js:2
  f.Callbacks.o.fireWith                      jquery.min.js:2
  e.extend.ready                              jquery.min.js:2
  c.addEventListener.B                        jquery.min.js:2</pre>

**Comment by iatek** [comment]
This should be resolved now.
