### ISSUE TITLE
pinterest with boards - suggestion

### ISSUE THREAD

**Issue by link82** [iatek/jquery-socialist#69]
I notice that the plugin will load just the boards cover if you have all your pins grouped in many boards (example user http://pinterest.com/gruppoicat) 

To get the list of all the pins you just need to append /pins to the id you pass to the script.

```
$('#pinterest-stream').socialist({
      networks: [
        {name:'pinterest',id:'gruppoicat/pins'}
      ],
      isotope:false,
      random:false,
      maxResults:100,
        fields:['text','image'],
      onSuccess:function(){
       //do some stuff
      },
      onFailure:function(){
        console.log('unable to retrieve social data');
      }
    });
```

Hope to help

**Comment by iatek** [comment]
Thanks for the tip!
