### ISSUE TITLE
I've fixed Facebook, Twitter and Pinterest

### ISSUE THREAD

**Issue by jimmynyny** [iatek/jquery-socialist#95]
Twitter requires some PHP because of secret keys, and I updated pinterest for their newer HTML.

Facebook probably requires PHP too, but I put the keys in the JS.

Is PHP violating the intent of this package? If so, I won't create a pull request.

**Comment by TeamRainless** [comment]
I don't think so. I'm dying to see your PHP solution. And what exactly is going on with facebook? All of a sudden it isn't loading all the posts. Do you have a link to your mods of socialist?

**Comment by jimmynyny** [comment]
Give me a bit and I'll throw it on BitBucket

**Comment by TeamRainless** [comment]
Thanks! Also... I've been having trouble with the facebook content. If I
have 50 profiles on my page, for example, the script might load 15 of them.
Have you run into anything like that?

**Comment by jlyon** [comment]
@jimmy0x52: Would you mind posting your code somewhere. I'd love to take a look? Thanks!

**Comment by jimmynyny** [comment]
Unfortunately I don't work there any more and the code is with them.

Check out the "who we are" page on www.charlestonorwig.com - everything but
the PHP is there. I can ask one of the developers if she would be willing
to share it.

On Monday, April 7, 2014, Jeff Lyon notifications@github.com wrote:

> @jimmy0x52 https://github.com/jimmy0x52: Would you mind posting your
> code somewhere. I'd love to take a look? Thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/iatek/jquery-socialist/issues/95#issuecomment-39800987
> .

## 

## 

http://twitter.com/jimmy0x52

**Comment by TeamRainless** [comment]
Why is this closed? Was it secretly fixed?

**Comment by jlyon** [comment]
@jimmy0x52: Thanks, this is perfect. If you wouldn't mind asking one of the developers to share the PHP code, I would really appreciate it. I'm guessing it was mostly oAuth logic.

@TeamRainless I don't know why it was closed.
