### ISSUE TITLE
Demo Never Loads

### ISSUE THREAD

**Issue by dschmidthawk** [iatek/jquery-socialist#98]
I've not been able to view any demo on the site's demo page using Chrome (latest) or IE11.  It just loads continuously.  This screen shot after 4+ minutes.

![jquery-socialist issue-20140212](https://f.cloud.github.com/assets/2288151/2151874/062bb20e-9412-11e3-83a9-ff62ebf60b2d.jpg)

**Comment by ghost** [comment]
I cannot get this thing to work either, same issue. If I cannot get the demo to load, why would I bother trying to get it to work on my site?

**Comment by iatek** [comment]
I guess you wouldn't bother ;-)

**Comment by dschmidthawk** [comment]
Hi Carol, not sure why this is closed.  Is there some way I can view or check out the demo?  I'd like to be able to recommend this to my clients but can't if they have the same viewing issues I do.  Is there a setting I'm missing in my browsers?
